# Generated by Django 3.1.6 on 2021-02-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('due_date', models.DateField(default='2021-02-06', verbose_name='Due Date')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed Status')),
                ('date_completed', models.DateTimeField(verbose_name='Date Completed')),
            ],
            options={
                'db_table': 'todoitems',
                'ordering': ['-date_created'],
            },
        ),
    ]
