# Generated by Django 3.1.6 on 2021-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, verbose_name='Date Completed'),
        ),
    ]
