# Generated by Django 3.1.6 on 2021-02-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210207_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Completed'),
        ),
    ]
